export default [
  {
    code: 'TB',
    name: 'Tampa Bay Rays',
    league: 'American',
    division: 'East',
  },
  {
    code: 'TOR',
    name: 'Toronto Blue Jays',
    league: 'American',
    division: 'East',
  },
  {
    code: 'NYY',
    name: 'New York Yankees',
    league: 'American',
    division: 'East',
  },
  {
    code: 'BAL',
    name: 'Baltimore Orioles',
    league: 'American',
    division: 'East',
  },
  {
    code: 'BOS',
    name: 'Boston Red Sox',
    league: 'American',
    division: 'East',
  },
  {
    code: 'CWS',
    name: 'Chicago White Sox',
    league: 'American',
    division: 'Central',
  },
  {
    code: 'KC',
    name: 'Kansas City Royals',
    league: 'American',
    division: 'Central',
  },
  {
    code: 'CLE',
    name: 'Cleveland Indians',
    league: 'American',
    division: 'Central',
  },
  {
    code: 'MIN',
    name: 'Minnesota Twins',
    league: 'American',
    division: 'Central',
  },
  {
    code: 'DET',
    name: 'Detroit Tigers',
    league: 'American',
    division: 'Central',
  },
  {
    code: 'OAK',
    name: 'Oakland Athletics',
    league: 'American',
    division: 'West',
  },
  {
    code: 'HOU',
    name: 'Houston Astros',
    league: 'American',
    division: 'West',
  },
  {
    code: 'ANA',
    name: 'Los Angeles Angels',
    league: 'American',
    division: 'West',
  },
  {
    code: 'SEA',
    name: 'Seattle Mariners',
    league: 'American',
    division: 'West',
  },
  {
    code: 'TEX',
    name: 'Texas Rangers',
    league: 'American',
    division: 'West',
  },
  {
    code: 'NYM',
    name: 'New York Mets',
    league: 'National',
    division: 'East',
  },
  {
    code: 'PHI',
    name: 'Philadelphia Phillies',
    league: 'National',
    division: 'East',
  },
  {
    code: 'WAS',
    name: 'Washington Nationals',
    league: 'National',
    division: 'East',
  },
  {
    code: 'MIA',
    name: 'Miami Marlins',
    league: 'National',
    division: 'East',
  },
  {
    code: 'ATL',
    name: 'Atlanta Braves',
    league: 'National',
    division: 'East',
  },
  {
    code: 'CHC',
    name: 'Chicago Cubs',
    league: 'National',
    division: 'Central',
  },
  {
    code: 'STL',
    name: 'St Louis Cardinals',
    league: 'National',
    division: 'Central',
  },
  {
    code: 'CIN',
    name: 'Cincinnati Reds',
    league: 'National',
    division: 'Central',
  },
  {
    code: 'PIT',
    name: 'Pittsburgh Pirates',
    league: 'National',
    division: 'Central',
  },
  {
    code: 'MIL',
    name: 'Milwaukee Brewers',
    league: 'National',
    division: 'Central',
  },
  {
    code: 'SD',
    name: 'San Diego Padres',
    league: 'National',
    division: 'West',
  },
  {
    code: 'SF',
    name: 'San Francisco Giants',
    league: 'National',
    division: 'West',
  },
  {
    code: 'COL',
    name: 'Colorado Rockies',
    league: 'National',
    division: 'West',
  },
  {
    code: 'LA',
    name: 'Los Angeles Dodgers',
    league: 'National',
    division: 'West',
  },
  {
    code: 'ARI',
    name: 'Arizona Diamondbacks',
    league: 'National',
    division: 'West',
  },
];
